@echo off
echo Running flutter create...
call flutter create --platforms=ios .
echo Running pub get...
call flutter pub get
echo Running launcher icons...
call dart run flutter_launcher_icons
echo Done!
